---DROP TABLES

DROP TABLE adresy CASCADE CONSTRAINTS;

DROP TABLE ekwipunek CASCADE CONSTRAINTS;

DROP TABLE ekwipunek_posterunku CASCADE CONSTRAINTS;

DROP TABLE incydenty CASCADE CONSTRAINTS;

DROP TABLE lasy CASCADE CONSTRAINTS;

DROP TABLE osoby CASCADE CONSTRAINTS;

DROP TABLE posterunki CASCADE CONSTRAINTS;

DROP TABLE pracownicy CASCADE CONSTRAINTS;

DROP TABLE rejony CASCADE CONSTRAINTS;

DROP TABLE rodzaje_inc CASCADE CONSTRAINTS;

DROP TABLE stanowisko CASCADE CONSTRAINTS;

DROP TABLE zatrudnienia CASCADE CONSTRAINTS;

DROP TABLE zmiana CASCADE CONSTRAINTS;

---DROP VIEWS

DROP VIEW INCYDENT_PRACOWNIK;

DROP VIEW ZATRUDNIENI_PO_2000;

DROP VIEW EKWIPUNEK_LASY;

DROP VIEW WYSWIETL_ZMIANY;

DROP VIEW ZAGRAZAJACE_INCYDENTY;

DROP VIEW PRACOWNICY_PER_MIASTO;

---DROP TRIGGERS

DROP TRIGGER DODANO_PRACOWNIKA

DROP TRIGGER DODANO_OSOBE

DROP TRIGGER DODANO_INCYDENT

---DROP SEQUENCES

DROP SEQUENCE adresy_seq;

DROP SEQUENCE osoby_seq;

DROP SEQUENCE pracownicy_seq;

DROP SEQUENCE stanowisko_seq;

DROP SEQUENCE zatrudnienia_seq;

DROP SEQUENCE zmiana_seq;

DROP SEQUENCE posterunki_seq;

DROP SEQUENCE rejony_seq;

DROP SEQUENCE lasy_seq;

DROP SEQUENCE incydenty_seq;

DROP SEQUENCE rodzaje_inc_seq;

DROP SEQUENCE ekwipunek_seq;