CREATE OR REPLACE TRIGGER DODANO_PRACOWNIKA
AFTER INSERT 
ON PRACOWNICY
BEGIN
dbms_output.put_line(SYSDATE);
END;
/
CREATE OR REPLACE TRIGGER DODANO_OSOBE
AFTER INSERT
ON OSOBY
BEGIN
dbms_output.put_line(SYSDATE);
END;
/
CREATE OR REPLACE TRIGGER DODANO_INCYDENT
AFTER INSERT
ON INCYDENTY
BEGIN
dbms_output.put_line(SYSDATE);
END;
/