---DROP VIEWS

DROP VIEW INCYDENT_PRACOWNIK;

DROP VIEW ZATRUDNIENI_PO_2000;

DROP VIEW EKWIPUNEK_LASY;

DROP VIEW WYSWIETL_ZMIANY;

DROP VIEW ZAGRAZAJACE_INCYDENTY;

DROP VIEW PRACOWNICY_PER_MIASTO;