---DROP TABLES

DROP TABLE adresy CASCADE CONSTRAINTS;

DROP TABLE ekwipunek CASCADE CONSTRAINTS;

DROP TABLE ekwipunek_posterunku CASCADE CONSTRAINTS;

DROP TABLE incydenty CASCADE CONSTRAINTS;

DROP TABLE lasy CASCADE CONSTRAINTS;

DROP TABLE osoby CASCADE CONSTRAINTS;

DROP TABLE posterunki CASCADE CONSTRAINTS;

DROP TABLE pracownicy CASCADE CONSTRAINTS;

DROP TABLE rejony CASCADE CONSTRAINTS;

DROP TABLE rodzaje_inc CASCADE CONSTRAINTS;

DROP TABLE stanowisko CASCADE CONSTRAINTS;

DROP TABLE zatrudnienia CASCADE CONSTRAINTS;

DROP TABLE zmiana CASCADE CONSTRAINTS;

---DROP SEQUNCES

DROP SEQUENCE adresy_seq;

DROP SEQUENCE osoby_seq;

DROP SEQUENCE pracownicy_seq;

DROP SEQUENCE stanowisko_seq;

DROP SEQUENCE zatrudnienia_seq;

DROP SEQUENCE zmiana_seq;

DROP SEQUENCE posterunki_seq;

DROP SEQUENCE rejony_seq;

DROP SEQUENCE lasy_seq;

DROP SEQUENCE incydenty_seq;

DROP SEQUENCE rodzaje_inc_seq;

DROP SEQUENCE ekwipunek_seq;